instance1/temp-retrieve/objects/DrChrono_Request_Log__c/DrChrono_Request_Log__c.object-meta.xml
<CustomObject>
    <label>Request Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>DrChrono Request Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

instance1/temp-retrieve/objects/Patient_Agreement__c/Patient_Agreement__c.object-meta.xml
<CustomObject>
    <description>This object is designed to be the source of truth of what form the patient has signed, been sent, or viewed to be able to track if a patient can have a service performed.</description>
    <label>Patient Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Patient Agreement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Agreement__c/fields/Date_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent__c</fullName>
    <description>When the document was sent</description>
    <encryptionScheme>None</encryptionScheme>
    <label>First Date Sent</label>
    <type>DateTime</type>
</CustomField>

instance1/temp-retrieve/objects/Patient_Agreement__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The patient account that this consent form was sent for.</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Consent_Forms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

instance1/temp-retrieve/objects/Patient_Agreement__c/fields/Patient_Agreement_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Patient_Agreement_Configuration__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of agreement sent to the customer. This configuration record will hold what document and different reasons why this client got this document.</description>
    <label>Patient Agreement Configuration</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Patient Agreement Must Be Active to be assigned to this agreeemnt</errorMessage>
        <filterItems>
            <field>Patient_Agreement_Configuration__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Patient_Agreement_Configuration__c</referenceTo>
    <relationshipLabel>Patient Agreements</relationshipLabel>
    <relationshipName>Agreement</relationshipName>
    <type>Lookup</type>
</CustomField>

instance1/temp-retrieve/objects/Patient_Agreement_Configuration__c/Patient_Agreement_Configuration__c.object-meta.xml
<CustomObject>
    <description>This will be where all of the different forms would be configured and be linked to the different external systems that would send this document. This will then assist any automation to make sure the document is sent at the right time.</description>
    <label>Patient Agreement Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Patient Agreement Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Agreement Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Agreement_Configuration__c/fields/Agreement_Id__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Id__c</fullName>
    <description>This is the Id that is stored in Biocanic to send with the initial request to internal API</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Agreement Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Patient_Agreement_Configuration__c/fields/Agreement_Source__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Source__c</fullName>
    <label>Agreement Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Patient_Agreement_Platforms</valueSetName>
    </valueSet>
</CustomField>

instance1/temp-retrieve/objects/Patient_Agreement_Configuration__c/fields/Recurrence_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Schedule__c</fullName>
    <description>How often does this consent form need signed</description>
    <label>Recurrence Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Once</fullName>
            </value>
            <value>
                <fullName>Per Visit</fullName>
            </value>
            <value>
                <fullName>Per Request</fullName>
            </value>
            <value>
                <fullName>X Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

outputs_backup_20260519_231959/production-metadata/HEAL-33647-patient-patient/classes/Patient_TestSuite.cls
@isTest
public with sharing class Patient_TestSuite {

    @TestSetup
    static void makeData(){
        // Create New Person Account
        Account account = new Account();
        account.FirstName = 'Test';
        account.LastName = 'Patient';
        account.BillingCity = 'New York';
        account.BillingState = 'NY';
        account.BillingPostalCode = '10001';
        account.BillingCountry = 'USA';
        account.BillingStreet = '123 Main St';        
        account.PersonEmail = 'test@10xhealthsystem.com';
        account.PersonMobilePhone = '1234567890';
        account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Patient Account Record Type').getRecordTypeId();
        insert account;

        // New Patient Agreement Configuration
        Patient_Agreement_Configuration__c agreementConfig = new Patient_Agreement_Configuration__c();
        agreementConfig.Name = 'Test Agreement Config';
        agreementConfig.Agreement_Id__c = 'bz0-000000000000000';
        agreementConfig.Recurrence_Schedule__c = 'Once';
        agreementConfig.Agreement_Source__c = 'Biocanic';
        insert agreementConfig;

        // New Patient Agreement
        Patient_Agreement__c agreement = new Patient_Agreement__c();
        agreement.Name = 'Test Agreement';
        agreement.Patient__c = account.Id;
        agreement.Patient_Agreement_Configuration__c = agreementConfig.Id;
        agreement.Date_Sent__c = Date.today();
        insert agreement;
    }

    public static void createPatientWithBirthMonth(String birthMonth, String gender) {
        // Create test data
        Patient_DS_Event patientEvent = new Patient_DS_Event();
        patientEvent.eventId = 'aZ000B000000000AAA';
        patientEvent.eventType = 'CreatePatient';

        Patient_DS_Patient patientData = new Patient_DS_Patient();
        patientData.firstName = 'Test';
        patientData.lastName = 'Patient';
        patientData.email = 'test@10xhealth.com';
        patientData.phone = '1234567890';
        patientData.birthdate = birthMonth + ' 8, 2023'; // Change the birth month here
        patientData.gender = gender;
        patientData.mobile = '1234567890';

        patientData.billingAddress = new Patient_DS_Address();
        patientData.billingAddress.city = 'New York';
        patientData.billingAddress.state = 'NY';
        patientData.billingAddress.zip = '10001';
        patientData.billingAddress.country = 'USA';
        patientData.billingAddress.street = '123 Main St';

        patientData.shippingAddress = new Patient_DS_Address();
        patientData.shippingAddress.city = 'New York';
        patientData.shippingAddress.state = 'NY';
        patientData.shippingAddress.zip = '10001';
        patientData.shippingAddress.country = 'USA';
        patientData.shippingAddress.street = '123 Main St';

        Patient_Patient.Request request = new Patient_Patient.Request();
        request.event = patientEvent;
        request.patient = patientData;

        List<Patient_Patient.Request> requests = new List<Patient_Patient.Request>();
        requests.add(request);

        HttpCalloutMockFactory mock = new HttpCalloutMockFactory(201, 'OK', 'OK', new Map<String, String>());
		test.setMock(HttpCalloutMock.class, mock);
		test.startTest();
		Patient_patient.Submit_Patient(requests);
		test.stopTest();
		// Assert logs were generated. Note, MakeAPIcall logs once.
		List<DrChrono_Request_Log__c> logs = [SELECT Id FROM DrChrono_Request_Log__c];
		// Assert.areEqual(3, logs.size());
    }

    @isTest
    public static void createPatientSuccess_January() {
        createPatientWithBirthMonth('January','Male');
    }

    @isTest
    public static void createPatientSuccess_February() {
        createPatientWithBirthMonth('February','male');
    }

    @isTest
    public static void createPatientSuccess_March() {
        createPatientWithBirthMonth('March','male');
    }

    @isTest
    public static void createPatientSuccess_April() {
        createPatientWithBirthMonth('April','female');
    }

    @isTest
    public static void createPatientSuccess_May() {
        createPatientWithBirthMonth('May','Female');
    }

    @isTest
    public static void createPatientSuccess_June() {
        createPatientWithBirthMonth('June','Male');
    }

    @isTest
    public static void createPatientSuccess_July() {
        createPatientWithBirthMonth('July','Male');
    }

    @isTest
    public static void createPatientSuccess_August() {
        createPatientWithBirthMonth('August','Male');
    }

    @isTest
    public static void createPatientSuccess_September() {
        createPatientWithBirthMonth('September','Male');
    }

    @isTest
    public static void createPatientSuccess_October() {
        createPatientWithBirthMonth('October','Female');
    }

    @isTest
    public static void createPatientSuccess_November() {
        createPatientWithBirthMonth('November','Female');
    }

    @isTest
    public static void createPatientSuccess_December() {
        createPatientWithBirthMonth('December','FeMale');
    }

    // Test Classes for Submitting Forms
    @isTest
    public static void sendConsentForms() {
        // Select the Patient Agreement and Patient Agreement Configuration
        Patient_Agreement__c agreement = [SELECT Id, Name, Patient__c, Patient_Agreement_Configuration__c FROM Patient_Agreement__c LIMIT 1];
        Patient_Agreement_Configuration__c agreementConfig = [SELECT Id, Name, Agreement_Id__c FROM Patient_Agreement_Configuration__c WHERE Id = :agreement.Patient_Agreement_Configuration__c LIMIT 1];

        Test.startTest();
        // Create test data
        List<Patient_DS_ConsentForm_RequestForms> consentForms = new List<Patient_DS_ConsentForm_RequestForms>();
        Patient_DS_ConsentForm_RequestForms consentForm = new Patient_DS_ConsentForm_RequestForms();
        consentForm.formId = agreementConfig.Agreement_Id__c;
        consentForm.salesforceAgreementId = agreement.Id;
        consentForms.add(consentForm);

        List<Patient_DS_ConsentForm_Request> consentRequests = new List<Patient_DS_ConsentForm_Request>();
        Patient_DS_ConsentForm_Request consentRequest = new Patient_DS_ConsentForm_Request();
        consentRequest.accountId = agreement.Patient__c;
        consentRequest.forms = consentForms;
        consentRequests.add(consentRequest);

        List<Patient_SendConsentForm.Request> requestWrappers = new List<Patient_SendConsentForm.Request>();
        Patient_SendConsentForm.Request requestWrapper = new Patient_SendConsentForm.Request();
        requestWrapper.request = consentRequests;
        requestWrappers.add(requestWrapper);

        HttpCalloutMockFactory mock = new HttpCalloutMockFactory(200, 'OK', '{"success":true, "errorMessage":"", "items":[{"salesforceAgreementId":"' + getPatientAgreementKeyPrefix() + '000000000000000", "formId": "asdf", "biocanicAssignementId": "123", "success":true, "errorMessage":""}]} ', new Map<String, String>());
		test.setMock(HttpCalloutMock.class, mock);
		Patient_SendConsentForm.Patient_SendConsentForm(requestWrappers);
		test.stopTest();
		List<DrChrono_Request_Log__c> logs = [SELECT Id FROM DrChrono_Request_Log__c];
		// Assert.isTrue(logs.size() >= 4);
    }

    //Helper methods
	private static String getPatientAgreementKeyPrefix(){
		SObject agreementObj = (SObject) Patient_Agreement__c.class.newInstance();
		return agreementObj.getSObjectType().getDescribe().getKeyPrefix();
	}
}